#!/bin/bash
first=1
while true
    do
    x=2
    while [[ $x -le 254 ]]
        do
        #0->no client;1->fresh client;2->server side up;4->tunnel is up

        str=$(sed "$x q;d" /home/$(hostname)/.config/voider/clients/occupants)
        if [[ ! $str -eq 0 ]]
            then
            if [[ $first -eq 1 ]]
                then
                sed -i "$x s/.*/1/" /home/$(hostname)/.config/voider/clients/occupants
            else
                if [[ $str -eq 1 ]]
                    then
                    /home/$(hostname)/.config/voider/server_up $x        
                    sed -i "$x s/.*/2/" /home/$(hostname)/.config/voider/clients/occupants        
                fi            
                if [[ $str -eq 2 ]]
                    then
                    if [[ ! -e /home/$(hostname)/.config/voider/punchit/running ]]
                        then                    
                        touch /home/$(hostname)/.config/voider/punchit/signal
                    fi                
                fi
                if [[ $str -eq 4 ]]
                    then                
                    ping -c 1 172.31.0.$x
                    if [[ $? -ne 0 ]]   
                        then
                        sed -i "$x s/.*/2/" /home/$(hostname)/.config/voider/clients/occupants        
                    fi
                fi
            fi    
        fi    
    x=$(( $x + 1 ))
    done

if [[ $first -eq 1 ]]
    then
    first=0
fi            

sleep 60
done

